### ISSUE TITLE
OSError: [WinError 6] ERROR_INVALID_HANDLE

### ISSUE THREAD

**Issue by scruel** [cosine0/dllhook#5]
(py37u32) K:\Program\Code\Python\Others>python -mdllhook "C:\Program Files (x86)\RedisDesktopManager\rdm.exe" test.py
[+] Opened a handle to pid: 11908
[*] Found Python library at: C:\ProgramData\Anaconda3\envs\py37u32\python37.dll
[*] Injecting Python into the process...
[+] Loaded C:\ProgramData\Anaconda3\envs\py37u32\python37.dll with handle 0x5ea30000
[*] Resolved addresses:
  - Py_InitializeEx:    0x5eb80994
  - PyRun_SimpleString: 0x5eb91507
[*] Initialized Python in the host process
[*] Waiting for client to connect on \\.\pipe\mayhem
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py37u32\lib\site-packages\dllhook\mayhem\tools\python_injector.py", line 214, in <module>
    main()
  File "C:\ProgramData\Anaconda3\envs\py37u32\lib\site-packages\dllhook\mayhem\tools\python_injector.py", line 202, in main
    client = NamedPipeClient.from_named_pipe(PIPE_NAME)
  File "C:\ProgramData\Anaconda3\envs\py37u32\lib\site-packages\dllhook\mayhem\tools\python_injector.py", line 139, in from_named_pipe
    raise ctypes.WinError()
OSError: [WinError 6] ERROR_INVALID_HANDLE。

**Comment by cosine0** [comment]
Thank you for reporting!
I'm aware that some features are not working stably as their depending libraries change.
I'm currently refactoring the core of binary handling code, but I'll look through this issue, and if it is easily fixable I'll give a quick fix to it.

And also, pull requests are always welcome!

**Comment by scruel** [comment]
Thanks, but I am using Frida now, will check back after you fix this!
